### PR TITLE
new-feature:add k3dict

### PR DESCRIPTION
**Pull request by IloveKanade**
The dictutil been modified according to the specification

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
what about renaming it to k3dict?
As far as I know the name`dictutil` is just for distinguishing it from the python native `dict`. 🤔

**Comment by IloveKanade** [comment]
> what about renaming it to k3dict?
> As far as I know the name`dictutil` is just for distinguishing it from the python native `dict`. 🤔

That makes f**king sense，I'll change it right away

**Comment by IloveKanade** [comment]
> what about renaming it to k3dict?
> As far as I know the name`dictutil` is just for distinguishing it from the python native `dict`. 🤔

down

**Comment by drmingdrmer** [comment]
> > what about renaming it to k3dict?
> > As far as I know the name`dictutil` is just for distinguishing it from the python native `dict`. 🤔
> 
> down

The travis CI said there might be something wrong...

**Comment by drmingdrmer** [comment]
I see... I've had once such a issue. travis CI does not follow repo renaming. 
We should remove the travis CI workflow!

@IloveKanade

**Comment by drmingdrmer** [comment]
remove the `.travis.yml` and see if CI passed...

And I'm gonna remove the travis from tmpl.

**Comment by IloveKanade** [comment]
> remove the `.travis.yml` and see if CI passed...
> 
> And I'm gonna remove the travis from tmpl.

I think that's working

**Review by drmingdrmer — APPROVED** [review]
LGTM

**Pull request merged**
